mapado_rest_client_sdk:
  # debug: %kernel.debug%
  # cache_dir: '%kernel.cache_dir%/mapado/rest_client_sdk_bundle/'
  entity_managers:
    foo:
      server_url: 'https://ticketing.mapado.net'
      request_headers:
        MyHeader: 'MyValue'
      mappings:
        prefix: /v1
        configuration:
          collectionKey: 'items' # default is "hydra:member"
        dir: '%kernel.root_dir%/../src/Foo/Bar/Entity/'
      cache:
        cache_item_pool: 'psr6_cache_provider' # default is null
        cache_prefix: 'my_prefix' # default is null